// app/layout.tsx
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>📍 1545 Birchmounth</div>
          <div>📞 (416) 606-1234 | 📠 (416) 123-4567</div>
          <div>🕒 M-W-Th 9am–6pm, T-F 10am–6pm, Sat 10am–3pm</div>
          
        </header>
        <nav>
            <a href="/">Home</a>
            <a href="/services">Services</a>
            <a href="/about">About</a>
            <a href="/contact-us">Contact</a>
            <a href="/products">Order Medications</a>
          </nav>
        <main>
          {children}
        </main>

        <footer>
          &copy; 2025 JzPharma. All rights reserved.
        </footer>
      </body>
    </html>
  )
}
